Controllers/ApplicationTypeController.cs
using Microsoft.AspNetCore.Mvc;
using Online_Store.Data;
using Online_Store.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Online_Store.Controllers
{
    public class ApplicationTypeController : Controller
    {
        private readonly ApplicationDbContext _db;
        public ApplicationTypeController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            List<ApplicationType> objList = _db.ApplicationType.ToList();
            return View(objList);
        }

        //GET - CREATE
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        //POST - CREATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ApplicationType obj)
        {
            if (ModelState.IsValid)
            {
                _db.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //GET - EDIT
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _db.ApplicationType.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }
        //POST - EDIT
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ApplicationType obj)
        {
            if (ModelState.IsValid)
            {
                _db.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }


        //GET - DELETE
        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _db.ApplicationType.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }
        //POST - DELETE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = _db.ApplicationType.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            _db.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Views/ApplicationType/Create.cshtml
@model ApplicationType

<form method="post" asp-action="Create">
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-info pl-3">Add ApplicationType</h2>
        </div>
        <div class="col-8">
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Name"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-8 offset-4 row">
                    <div class="col">
                        <input type="submit" class="btn btn-info w-100" value="Create" />
                    </div>
                    <div class="col">
                        <a asp-action="Index" class="btn btn-success w-100">Back</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-4">
            @*Keep this empty*@
        </div>
    </div>
</form>

@section Scripts{

    @{ <partial name="_ValidationScriptsPartial" />}

}

Views/ApplicationType/Delete.cshtml
@model ApplicationType

<form method="post" asp-action="DeletePost">
    <input asp-for="Id" hidden />
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-info pl-3">Edit ApplicationType</h2>
        </div>
        <div class="col-8">
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Name"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Name" disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-8 offset-4 row">
                    <div class="col">
                        <input type="submit" class="btn btn-danger w-100" value="Delete" />
                    </div>
                    <div class="col">
                        <a asp-action="Index" class="btn btn-success w-100">Back</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-4">
            @*Keep this empty*@
        </div>
    </div>
</form>

Views/ApplicationType/Edit.cshtml
@model ApplicationType

<form method="post">
    <input asp-for="Id" hidden />
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-info pl-3">Edit ApplicationType</h2>
        </div>
        <div class="col-8">
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Name"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-8 offset-4 row">
                    <div class="col">
                        <input type="submit" class="btn btn-info w-100" value="Update" />
                    </div>
                    <div class="col">
                        <a asp-action="Index" class="btn btn-success w-100">Back</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-4">
            @*Keep this empty*@
        </div>
    </div>
</form>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
      }
}

Views/ApplicationType/Index.cshtml
@using Online_Store.Models
@{
    ViewData["Title"] = "ApplicationType Page";
}
<div class="container p-4">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">ApplicationType List</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-controller="ApplicationType" asp-action="Create" class="btn btn-primary">
                <i class="fas fa-plus"></i> &nbsp; Create New ApplicationType
            </a>
        </div>
    </div>

    <br /><br />

    @model List<ApplicationType>
    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Id
                    </th>
                    <th>
                        Name
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                    <tr>
                        <td width="50%">@obj.Id</td>
                        <td width="30%">@obj.Name</td>
                        <td class="text-center">
                            <div>
                                <a asp-controller="ApplicationType" asp-route-Id="@obj.Id" asp-action="Edit" class="btn btn-info mx-2">
                                    <i class="fas fa-edit"></i>
                                </a>
                                <a asp-controller="ApplicationType" asp-route-Id="@obj.Id" asp-action="Delete" class="btn btn-danger mx-2">
                                    <i class="fas fa-trash"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p> No ApplicationType exists. </p>
    }

</div>